export enum TicketingState {
  NOT_IN_QUEUE = 'NOT_IN_QUEUE',
  WAITING = 'WAITING',
  ACTIVE = 'ACTIVE',
  RESERVING = 'RESERVING',
  PAYING = 'PAYING',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
  LEFT = 'LEFT',
  CANCELLED = 'CANCELLED',
}
